apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: docker.io/vaultwarden/server
      tag: 1.28.1-alpine
    env:
      TZ: America/Detroit
      SIGNUPS_ALLOWED: "false"
      SHOW_PASSWORD_HINT: "false"
      DOMAIN: https://vault.zynthovian.xyz
      ADMIN_TOKEN:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secret
            key: admin-token
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/appName: "Vaultwarden"
          hajimari.io/icon: mdi:account-lock
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Vaultwarden"
          gethomepage.dev/icon: vaultwarden
        hosts:
          - host: &host vault.zynthovian.xyz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: vaultwarden
        mountPath: /data
