---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
