apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: default
data:
    admin-token: ENC[AES256_GCM,data:BS5X0mCB436HdVvgskFROVbp/c8x+Or8tF/x63ahJiPBxHqfeihnTA6kkOS7phDvH+AQK0wj4WmxhjvPQ42NSQ==,iv:8SeQgmf3LNDfJhu1/pz7bSFyLVCwTcMyluRRiQHy+hM=,tag:IILEEuAHgMf8Z+mLQjQZaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNkdWQTNQSHVXYnBZUElw
            UlRSeng2RDErbGZ0YldqZUNMOC9pc1V2U1VzCmR0eVpSTmdmQWk4VGxFSVRwNGZZ
            YmQ2V25Eem93V0VoRTE0MWdZN1pqaFkKLS0tIGM0NXlQTVZPMTNBSTUvVmFkdGpj
            emRzTHVZZFBaNENUUXpteFBkREhPUE0KdzwGHn2PK/RtO0mTmayJlm85VIENYlWq
            jD21aUsx7YLvvZ4QZNUgFuQNQPHBxRcOXOBopyytvKXL+DuY+W3jIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-15T02:44:38Z"
    mac: ENC[AES256_GCM,data:6amVU4vOwq9Eve4ZtiGhULY0JzKUAYiVPruXqgZDVe50JTlUe7wtEXsdhrlFefkh7BBmy4ljrfZEQi4vXK/4BQ5rBCOwKQlaqIXv/P+MJ/RVvccbHPSJAFYT4J41o86CDeAYzYz27yYnFOIclM2SdpPZ3uE/7YVVPYpCTvpjuDg=,iv:MmGDpMynUIhL8v/pkRQtSPbf1wjuFb2mqnv0zeAIUcg=,tag:ms9cRgNKKcJGbXUWCxAEbQ==,type:str]
    pgp:
        - created_at: "2023-02-15T02:44:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAiT8v3xNfkIgxqbaYCQS9uOIsno2hyv1FgCOZUqjdiTww
            1wew9q6znVDOQLkyVJPcwJ4Il9/mk1P5Vvcw7tBfYaDbzlkvYk9tidXctIMjW+8u
            0pUBMYTFMDzeixnzEhiK6scqA4y1jgsxCT6sHpeS2GSg7Dc36TD4HiySNEKwhua7
            vMZModQUPOl7frvrIsnSivwWEjeUdIeOxUTCEkDK8Zpj1qTgiuHPeqkaimdjakAa
            bgiDXlYI4x1NL1Wahno5cHcfY53B2EvOcKbb/XPqWlvXPARXCAK+VuxQVswDLX6m
            Du0rN5cC9A==
            =pix3
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
