---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox-postgres
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: library/postgres
      tag: "14"
    env:
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: netbox
            key: DB_PASSWORD
      POSTGRES_DB: netbox
      PGDATA: /var/lib/postgresql/data
    podSecurityContext:
      runAsUser: "${SECURITY_CONTEXT_RUN_AS_USER}"
      runAsGroup: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
      fsGroup: "${SECURITY_CONTEXT_FS_GROUP}"
    service:
      main:
        ports:
          http:
            port: 5432
    persistence:
      data:
        enabled: true
        mountPath: /var/lib/postgresql/data
        existingClaim: netbox-data
        subPath: netbox_db
    podAnnotations:
      secret.reloader.stakater.com/reload: netbox
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox-redis
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: docker.io/library/redis
      tag: "7"
    command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
    env:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: netbox
            key: REDIS_PASSWORD
    persistence:
      data:
        enabled: true
        path: /data
        existingClaim: netbox-data
        subPath: netbox_redis
    service:
      main:
        ports:
          http:
            port: 6379
    podAnnotations:
      secret.reloader.stakater.com/reload: netbox
