---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox-postgres
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: library/postgres
      tag: "14"
    env:
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: netbox
            key: DB_PASSWORD
      POSTGRES_DB: netbox
      PGDATA: /var/lib/postgresql/data
    podSecurityContext:
      runAsUser: "${SECURITY_CONTEXT_RUN_AS_USER}"
      runAsGroup: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
      fsGroup: "${SECURITY_CONTEXT_FS_GROUP}"
    service:
      main:
        ports:
          http:
            port: 5432
    persistence:
      data:
        enabled: true
        mountPath: /var/lib/postgresql/data
        existingClaim: netbox-data
        subPath: netbox_db
    podAnnotations:
      secret.reloader.stakater.com/reload: netbox
    initContainers:
      config:
        image: docker.io/library/busybox:latest
        env:
          GID: "${SECURITY_CONTEXT_RUN_AS_USER}"
          UID: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
        command:
          - /bin/sh
          - -c
          - |
            echo "Initializing files..."
            mkdir -v /mnt/netbox_db
            chown -v $UID:$GID /mnt/netbox_db
        volumeMounts:
          - name: data
            mountPath: /mnt/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox-redis
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: docker.io/library/redis
      tag: "7.0.8-alpine"
    command: ["/bin/sh", "-c", "redis-server --appendonly yes --port 6379 --requirepass $REDIS_PASSWORD"]
    env:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: netbox
            key: REDIS_PASSWORD
    persistence:
      data:
        enabled: true
        path: /data
        existingClaim: netbox-data
        subPath: netbox_redis_main
    service:
      main:
        ports:
          http:
            enabled: false
          redis:
            enabled: true
            protocol: TCP
            port: 6379
          cache:
            enabled: true
            protocol: TCP
            port: 6378
    podAnnotations:
      secret.reloader.stakater.com/reload: netbox
    additionalContainers:
      cache:
        image: docker.io/library/redis:7.0.8-alpine
        command: ["/bin/sh", "-c", "redis-server --port 6378 --requirepass $REDIS_CACHE_PASSWORD"]
        env:
          REDIS_CACHE_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: netbox
                key: REDIS_CACHE_PASSWORD
        volumeMounts:
          - name: data
            subPath: netbox_redis_cache
            mountPath: /data
