# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: netbox
    namespace: default
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:PNex9iaJoKU4bB1cy3iF0Vfla0kkbY8SZ00qUsh8c9dH4tI=,iv:67Cgsui+mqUSYFMXD0TNE4ky+Un16VckjFTkTiOoz2Q=,tag:4ltcbvfwkgMgNOvcKs3iOg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:mK2pZDWLj45EvyT/5yvb6RimQTh52ncCKQTN03buoIz8Hdr5,iv:/JISkpDqU09R3eSV3C2J+taBgMIsRzaZQ0bH3iZo8k8=,tag:sLajUSeWzfakT9Wne1ppFQ==,type:str]
    REDIS_CACHE_PASSWORD: ENC[AES256_GCM,data:uoYPuWhBXYY57RG0Oli+7OorhoHElxvmgZOBD9a+SdO4vd7Lig==,iv:6VAgUzayE+KbEKCFLFvBQ+Pl3llRsFKN9qhky6tT6Yo=,tag:6dk075/POq4WQQr2RK7uRA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:rKH2llgpMPIxiX5/EdTK1pLp5w3gz0K2ShPwfKhhLIa6OYrbpo6jgoNeuga8jJ5tExk=,iv:mOnArBDYLRgO6G3GoYuIoF4QWrjYL+JgUoWyV5Qq0dw=,tag:iitFTY/CYYG96s6Q6D32wg==,type:str]
    #ENC[AES256_GCM,data:S34UTCE9uoWubRvwSLbQkD1CguheI6WWHtYykNfqsADlkbRX5N6+SminSzQGjARSH9/rHJBA1WO9Wg==,iv:0kpNf9G9C07pfYfAX122Ya0+5IYpdieWdp/GWLOHBhg=,tag:xnFd1LCq0Ss1nr0NTCtnVQ==,type:comment]
    SUPERUSER_NAME: ENC[AES256_GCM,data:ZtXmUZa8EEknQD2rt2uVE1bfruJD32MRB0NCPz7FK84h2jzZcA==,iv:bqM9bEu604YKEzco7r546s8bQxvaZZn30Na83nNg5E4=,tag:KzzvRu+TecvFDv7nE7jGtw==,type:str]
    SUPERUSER_PASSWORD: ENC[AES256_GCM,data:5/SAWbbdw1xG2A+UjzYSrTaT4zbqC1tC6kGMaghHeFfuZafNapo=,iv:JfipvFqy1TzrG9E2B+gLs5mV4pqTCz2UinXgBpo2ybY=,tag:G31fSDJndNerux+AJM/2qQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Q3B2TE0yNUdBNXdVTHZX
            VkhZMFNpNHl2eDlzNnNGc2Nic2lQYmZtU1VrCktBS211WkVCMGdjK1JncytvSTZN
            aWRWZUJFaWU0cjJ4cTF6RHkxOVFsUVEKLS0tIG1vTmpFa3NzOHFxOFByL25XZmFo
            dUZiQXc3L1dSbzI1SGQrSW9FVXRwSTQKr+EHjSVw5iq85EQjoyk0hty6sfAYcKtZ
            yOYTSkQVL0Cr+ToH8SlFSsYDs7050bZPU4ckn40yseRaHfv1xUjdsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-22T11:19:29Z"
    mac: ENC[AES256_GCM,data:QBX5vZ/Q5frUBH6LePvJ3IzdX8jOnSYn17BfNpdnRoIjKdKfBLYtKca04CDiaqdzRptGT+eiAwntd3ZyItKXWe/CJAgpmEa8W9BnSXn74t5rXeEo6dJheHitYoyJFdVjNQUlMZV5DTnGZzf+bbcWf7JKxosHOBB2QPY0puf9nnw=,iv:cj9RkWe8oN+zYiNWjY7/z86Y7yg9hqOfuZBdOHXaI2c=,tag:MEgbgvb63aXQ9BC8vkTRzQ==,type:str]
    pgp:
        - created_at: "2023-02-22T11:19:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAkrravMrUY/xKbUEQmxJwbjtYfTKJ475dOHrSY9yYSRcw
            lEgntfdL+cFeNgkl0z2f3RvhnFxioQwiSqfjJYx1v6M3imBlh2Jt6oXK7paWCkAw
            0pMBe7UV9BJX7jcmOjJ+TsCNNfZdV+qHp4OL9hUZBNodRvqDTAAYJBTLjD36sHBD
            3ge9ORQ4UulO/vlY5dipAwa7WcuRHrjk45EJnjdYXCVdC4IuK3XpdchsEjs4uEfM
            qVP6xtNqMBEz/dv84CMLefOT2Di/IJ1vAtlR5bCkojLm9mMp+HdM6sbN9e6XDD+g
            eJJUbU0=
            =UXhR
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
