# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: netbox
    namespace: default
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:DLwRmzvbcnYCN90V1gbOEXbmVXCdER4KygZR3YWq1xk5yErdLGydo6N5EMB2srx3,iv:XtqoDxOLZF4YqAOkXrt6jhiAF+iM0rSTd0ZEXP3+zwA=,tag:tnukWqAGM/j+wvBF0pnVyQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:D9iVHJO3q91WEIga364rVq889o3BDEjmxP08OlmX7nBMsCIaIF4KqkdL52Am/iiu7cBUZw==,iv:Y3sWjtVx/HUi/rGHo0r/LkCk+VCl7zeg9QBQ+SMFotw=,tag:IC69IyKa/GNrLbXmUzOThQ==,type:str]
    REDIS_CACHE_PASSWORD: ENC[AES256_GCM,data:nEvB2Pbe8oPxApdIdTzCBuWU/fcKwiHTttsjPhn9XNOpK8zx7UxcgLD/rN2l7m5O,iv:t9HH+eJybSQwkncl/siBEV43cK3Yl+/nPK009uLcsiU=,tag:DTpgxNrAToFutUUTRvteqg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:lAvGfFSn6AY+gMUHnPtiTmygENNDcawM/DUGFKL3MLKDuTdkfauwzEX2MMB22Icw,iv:qZ9xh6sh+SaWvw4uWu5nMbLCOrBgt6FWhT3wKH8lSbk=,tag:fChdW5ivOI0VVTyTdLzdMg==,type:str]
    #ENC[AES256_GCM,data:3RuFGAtL+y8v/1XcpVBXb+yrnSAq,iv:cf3Srioz+3J5Qvoc5j5rYWOOIEmWSbv5lwqlCJ0V+Hk=,tag:YAmMJlOWERoMWa97x5pecw==,type:comment]
    SUPERUSER_NAME: ENC[AES256_GCM,data:DKbpkpz9itebZEtp,iv:pYmdm9SugxO/IJLCctMZgbsPGQkom/+Z2b9LIs7p5E4=,tag:5ZSUlNVuOkhlZYqz3IT/lw==,type:str]
    SUPERUSER_PASSWORD: ENC[AES256_GCM,data:LWVWC2HXMWu5ZY8yC1molRjtQ6bDDHfX7dLxRdJu0L/Cr5+nJc+D051lWkRrWoIYDrctLgp0IMc=,iv:GC2M4wxacPpo2vGSTfw8wkQ+dVWxF/h/7uDp44DiqwU=,tag:jc8bWLzj1MocIWTfI1sQcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONWNDeGt5SjRmSUhqd2dJ
            MDRMQzdVd0Q1eGI3cEMzSVBVZXlqck1SU1Y4CmlpRFdqWFNUV2Q2Y1FZTkFySkVB
            a3pzTnVHUTRvaXN2WVZaMlRUK1p3akkKLS0tIENJeEJFWExSL1hmLzhJMUhkcUNU
            czZLZlBPYzVzekFackpqSGFBRkw4K0kK5mVi0Nx6DhIan7DUqPyfGqgnP0PJ1jQB
            gQ9BqGzrQU2jWKB2/Alf5h9cmP7P6hkYSqviG5yotmIMp+Hkwu0IRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-22T02:06:11Z"
    mac: ENC[AES256_GCM,data:Ho0aWYhnnn+jvgHvBt/Jq6o3kc5ejcsQDFOiTEAkigGwONAI1CpEFnBpklK9mE6pZWBShg+lzahrEzBnXXsS+5e46I1k7DxXJCRa8IftIs5JX3+uen2Kv331fH6X3uXAcUVTIEcOl5RbSUEKZ3gueqaeCxkHsrcOyh3opcCyhKk=,iv:yBDrfWKv5Nag9ew7Kzp99QDMuFwf2Ob4wffozkHwC1c=,tag:0F6YKs94jvdGqRsvHHXhYQ==,type:str]
    pgp:
        - created_at: "2023-02-22T02:06:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAy1zW/uUlk1Uu1po5tGLWe3QkhEB+snmchyCjU+y3jxYw
            p45ewYSTQsXUWwESfcdY5zfOODewl8vwA5tU2gueO49QE3atn8E/mxRfez1xN6LJ
            0pgBCbu7XcWQ1Y8FtRc7CVHFJ68XYwasn0Y9EEHdYSEVtSBmviNBX2LTWhlY2QzV
            e0ZXZA4b4z+chfge49nvs0HJVDv6/UBOZqNdzg4fjFsM9crdWy1nP0tYKRev6v8Q
            jkvG578BCc2aif9dV0rVcj9eGsv0RCAtP3Yq5UNF7QsdjVBC9Oy1cIgXtG205Gsm
            fMg72+H6h1WJuA==
            =OwwE
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
