---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app snmp-exporter-mikrotik
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    image:
      repository: quay.io/prometheus/snmp-exporter
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: *app
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: *app
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      namespace: monitoring
      params:
        - name: mdf-00-crs328-a
          module:
            - mikrotik
          target: 172.22.0.126
      path: /snmp
      scrapeTimeout: 30s
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance