# https://github.com/netbox-community/netbox-docker/wiki/Deployment

# Plugins:
# https://github.com/mattieserver/netbox-topology-views

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app netbox
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      # https://hub.docker.com/r/netboxcommunity/netbox/
      repository: docker.io/netboxcommunity/netbox
      tag: latest
    # https://github.com/netbox-community/netbox-docker/blob/release/env/netbox.env
    # https://demo.netbox.dev/static/docs/configuration/required-settings/
    # https://demo.netbox.dev/static/docs/configuration/optional-settings/
    envFrom:
      - secretRef:
          name: *app
      - configMapRef:
          name: *app
    podSecurityContext:
      runAsUser: "${SECURITY_CONTEXT_RUN_AS_USER}"
      runAsGroup: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
      fsGroup: "${SECURITY_CONTEXT_FS_GROUP}"
    persistence:
      data:
        enabled: true
        existingClaim: netbox-data
        subPath:
          - path: netbox/config
            mountPath: /etc/netbox
          - path: netbox/media
            mountPath: /opt/netbox/netbox/media
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:lan
        hosts:
          - host: &host "netbox.zynthovian.xyz"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    additionalContainers:
      worker:
        image: docker.io/netboxcommunity/netbox:latest
        envFrom:
          - secretRef:
              name: *app
          - configMapRef:
              name: *app
        command:
          - /opt/netbox/venv/bin/python
          - /opt/netbox/netbox/manage.py
          - rqworker
        volumeMounts:
          - name: data
            subPath: netbox/config
            mountPath: /etc/netbox
          - name: data
            subPath: netbox/media
            mountPath: /opt/netbox/netbox/media
      housekeeping:
        image: docker.io/netboxcommunity/netbox:latest
        envFrom:
          - secretRef:
              name: *app
          - configMapRef:
              name: *app
        command: [/opt/netbox/housekeeping.sh]
        volumeMounts:
          - name: data
            subPath: netbox/config
            mountPath: /etc/netbox
          - name: data
            subPath: netbox/media
            mountPath: /opt/netbox/netbox/media
