# yaml-language-server: $schema=https://gist.githubusercontent.com/james-d-elliott/756de37a4398b3445072a60d674905c6/raw/ce90833b1ce145cb701184557dd964fa7546f19a/jsonschema.json
---
server:
  address: tcp://0.0.0.0:80
  disable_healthcheck: true

telemetry:
  metrics:
    enabled: true
    address: "tcp://0.0.0.0:8080"

log:
  level: trace

theme: dark

default_redirection_url: https://auth.zynthovian.xyz

webauthn:
  disable: true

duo_api:
  disable: true

totp:
  issuer: authelia.com

session:
  name: authelia-homelab
  domain: zynthovian.xyz
  redis:
    database_index: 14
    host: redis.default.svc.cluster.local
    port: 6379

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules:
    - domain: "grafana.zynthovian.xyz"
      policy: bypass

notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt

authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 1m
  ldap:
    address: "ldap://glauth.default.svc.cluster.local:389"
    timeout: 5
    start_tls: false
    # Search Parameters
    user: cn=glauth,ou=svcaccts,dc=zynthovian,dc=xyz
    base_dn: dc=zynthovian,dc=xyz
    users_filter: '(&({username_attribute}={input})(objectClass=posixAccount))'
    groups_filter: '(&(memberUid={username})(objectClass=posixGroup))'
    additional_users_dn: ou=people
    attributes:
      display_name: givenName
      group_name: cn
      username: uid
      mail: mail

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret: $pbkdf2-sha512$310000$ZA.ch81TBBtc3pX0VW77UQ$wYgNLYtk1i38s2c7oZjvhXNnhKDQkhsCcTHvmYi8eTQFrdT8AzQdv3ct9pibvefsgKZClm2IJFGRFwerRtcQTw
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.zynthovian.xyz/login/generic_oauth"]
        userinfo_signing_alg: none