---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-pod-gateway-downloads
  namespace: flux-system
spec:
  path: "./kubernetes/cluster-0/apps/vpn/pod-gateway/downloads"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-as-code
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: pod-gateway-downloads
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m