---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - pgp:
          - 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
        age:
          - age16atsrnff28efjkx3c5hmy88gwgwv5cpma0xkyjjw95vcw8kstp9sf4lf7w
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - pgp:
          - 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
        age:
          - age16atsrnff28efjkx3c5hmy88gwgwv5cpma0xkyjjw95vcw8kstp9sf4lf7w
