apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  selector:
    # Editor complains if spec.selector is empty, despite using fancy kustomizations
  template:
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: default
      dnsPolicy: Default
      containers:
      - name: "coredns"
        image: "coredns/coredns:1.9.4"
        imagePullPolicy: IfNotPresent
        args: [ "-conf", "/etc/coredns/corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns/corefile
          subPath: corefile
        - name: config-volume
          mountPath: /etc/coredns/zones/zynthovian.xyz.db
          subPath: zynthovian.xyz.db
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - {containerPort: 53, protocol: UDP, name: udp-53}
        - {containerPort: 53, protocol: TCP, name: tcp-53}
        - {containerPort: 853, protocol: TCP, name: tcp-853}
        - {containerPort: 9153, protocol: TCP, name: tcp-9153}
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      volumes:
        - name: config-volume
          configMap:
            name: coredns
            items:
            - key: corefile
              path: corefile
            - key: zynthovian.xyz.db
              path: zynthovian.xyz.db
