---
- import_tasks: os-network.yml
  tags:
    - os

- import_tasks: k3s.yml
  tags:
    - k3s

- name: Ensure all nodes have iscsi utils
  ansible.builtin.dnf:
    name: 
      - iscsi-initiator-utils
      - libiscsi
    state: present

#- import_tasks: home-dns.yml
#  when: "'k8s-0' in inventory_hostname"
#  tags:
#    - home-dns


- name: Template BGP configmap for cilium
  ansible.builtin.template:
    src: cilium/cilium-bgp-configmap.yaml.j2
    dest: /tmp/cilium-bgp-configmap.yaml
  delegate_to: localhost
