---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actual
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: jlongster/actual-server
      tag: 23.7.0-alpine
      pullPolicy: IfNotPresent

    service:
      main:
        ports:
          http:
            port: 5006

    env:
      PORT: "5006"
      TINI_SUBREAPER: 1

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Actual"
          gethomepage.dev/icon: actual
          hajimari.io/name: "actual"
          hajimari.io/icon: cash-multiple
        hosts:
          - host: &host "{{ .Release.Name }}.zynthovian.xyz"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "tls.{{ .Release.Name }}"
            hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: actual-data
        mountPath: /data
