
---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./calico.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./kubernetes-dashboard.yaml
  - ./kyverno.yaml
  - ./longhorn.yaml
  - ./metrics-server.yaml
  - ./prometheus-community.yaml
  #- ./rook-ceph.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml

