---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mysql-operator
  namespace: flux-system
spec:
  interval: 2h
  url: https://mysql.github.io/mysql-operator/
