---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-externaldns-shared
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/networking/external-dns/shared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-as-code
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-externaldns-external
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/networking/external-dns/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-as-code
  wait: true
  dependsOn:
    - name: cluster-apps-externaldns-shared
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-externaldns-internal
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/networking/external-dns/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-as-code
  wait: true
  dependsOn:
    - name: cluster-apps-externaldns-shared