---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-dns
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/external-dns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-as-code
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
