---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: default
spec:
  volumeName: vaultwarden-data
  accessModes: [ ReadWriteOnce ]
  volumeMode: Filesystem
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-data
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: vaultwarden-data
