apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-primary
  namespace: database
spec:
  instances: 3
  tlsUseSelfSigned: true
  router:
    instances: 1
  secretName: mysql-primary-secret
  imagePullPolicy : IfNotPresent
  baseServerId: 1000
  version: 8.0.34
  serviceAccountName: mysql-primary-sa