apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    gf_security_admin_user: ENC[AES256_GCM,data:cVGE6po=,iv:LMqVIjeSIpfaZk68Cs9kV3wFRK+CGIR7g73SYs/Lw3g=,tag:AVAWYnIncK5M6eFZsbJ/wg==,type:str]
    gf_security_admin_password: ENC[AES256_GCM,data:x0uMR0vZjpPhyKy+KPxmfjK7SpD3jtWzrJ0=,iv:GCkmynUrZ+zAVWPp+BuqCs4+WklE+WAhbb9Vl1jgJ8k=,tag:CO+UNaQv8x95tOZd/LT7UQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Mmc2aW5DRDlZOFVHakY0
            MEZEdWpmbTI0bWlJS0hUUlBFaENYWGRnSmhrCk80bmtjeUR5ei8zMUJXU0ZMZHY0
            UW8yTkNGa2UxYTFLQkxxcjF6OWIxSVkKLS0tIHd2R0tBKzZ1SGE1dFRvRi9ZZkty
            ZkZ3M3dBRFdhZDFBTmR3WVc1c09kd1UK+3Hj2OlmQADL6tUNNhgTcZYnTsWgpMTw
            dFyJtLzwxMfPM/aydXoLJZawZLkdww5qs7x4uZ/xyRaJdgynk3BHBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T11:00:55Z"
    mac: ENC[AES256_GCM,data:rWVHqiO240SG/IkPPG/4ZadBJ1eilxDPc746bgX/d019JcihtVrT0GyZUc41ubqCXXcm06QMDMuqsJJyrtXEgGPuYFMdF8urXBPstLozeC9XWIs/cum0FvFnrYc7YrPzR+iI42L7/ppeNp6NbPcOVON+DVFLqFSQbBx9uYldawc=,iv:sWLJsoz8maJcQ81pfYMVTFbiRWrfFtCw15sjSG/spLU=,tag:tdbmi9qEwwOiiAG3fBjRsQ==,type:str]
    pgp:
        - created_at: "2023-06-26T11:00:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdA7YX0+ZG7GKy9cVYU7A/vXZCS2HBfEs7nv2T5qzkFWCQw
            c4FQkJixiV/x5cx+MSkGpBLYse7tTwC9zJEuoo8gJsZjpCvyzGca2poMYoRsnXIT
            0pQB8EdAQN9MX2mnoVHUiusdgV13ew6CTWpEx9hBkVUUvZZ99HHsMMLCP1ysDFZu
            a1z5axfYRdCM+iIZFs1XiKcWGPvbeFZ6O0R9gYZqnGlibjce86B2a9RVaJ7alszD
            1lOvVumjUEKGAo/enM2PtwbtLulpxhbh61oFXcsQV1RZUZkjFjGYft+gc/cF6R0q
            Xb8UPRD/
            =6Lhz
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:0AtuEAxIS9GGUnCd,iv:ggWya6P3RL5VntVxGqe8WoXfhjmwN6VMuql7Y49LCc4=,tag:DuZccfjdXLu0sS70hr33Lg==,type:comment]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:GmD5bHg7wBg=,iv:cd1UeB5qOMLMoF2Xn3PKzgjJ43OTakHsWzmViZCedkw=,tag:9Y6ULso5FdXP6MC2b5w+Bg==,type:str]
    GF_DATABASE_NAME: ENC[AES256_GCM,data:8DqPy8E3PQ==,iv:IGm/pOh2GFIQVE/rRa6/a4BEO9a9OwTnprfisYEk7gU=,tag:DesnYDSnagJij7K3cOqLhA==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:tVl9Y9lXbCzziOuyTUoTwzV1Yq0lp5InoXIFgdsO+0Ex2GloaV7XVVQXdA==,iv:F4OG5K+GyCf0LivMT9arIzRbsgsya4B8N4y+yXC4DoA=,tag:E/7u5HwHSSVwN3AzfWUcvw==,type:str]
    GF_DATABASE_USER: ENC[AES256_GCM,data:CenungiBTQ==,iv:k7A5alQA/5P1QTwegWraD85UvdR4e5zK623Ff1A99Gs=,tag:bDjEF8awEKqK34uxAvSyJg==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:SPrUw9c5hnN51dCb9QaNaXfjoTwnYSmcUYw=,iv:8K16xjycxqmFvIK/MMVkpREA1EqnKt8sMCpBS4UsbQw=,tag:vUuXsJj3usSem7533wq1Kg==,type:str]
    GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:HRvMI7jlSg==,iv:NbuIk6niVqPv0CpNEtPcGOtlv8LbE4xmKCDOf/L4igg=,tag:11saOSmoAhbudGaTPZVwDA==,type:str]
    #ENC[AES256_GCM,data:rnRymEUQZqM+JSuXeChCRAEzPSJSb+XCngpNylrFhmaRdYKKyUQNDyZ/2Vk154PzpLEBihPWLipyB7A84xnRV5D6IvHc6P0uU1XLpNqbrbFpW9w3h+B8E5oJ,iv:OpceNo65IV6DxEhmNWhrFcwUhGH2sWRMU8zlya6fgV8=,tag:iP6QOKtJIh0j2nZjL0pynA==,type:comment]
    #ENC[AES256_GCM,data:L3kzQssJXXYpDXbC4OoASObu,iv:e7rhSDXh25wD7WLJM+HLYpMtmz9Ne+fo6O9KsR+Se/c=,tag:xC5s2cKJAQoQIfqzwAmC+Q==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:kkYOkh6XUg==,iv:/xek09Efx31OPNqk+AaA6duvyfK35Y3hUvuVFFYX6GY=,tag:XUhhNe0lssNzVax+LVtiWQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:gmVwxSvfnYKZc5tMRbM47MQa1Mz2i4YsCKj25tIaTDE1pqs13vA=,iv:QQWoDGW3IHocITQHf78uP0Suo3RJ+8v9vVsVtIlW6dA=,tag:YLFIjinaHOaWVnEWEOfw7w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ABZ+DG5CV1+nHaTilYwhVFHZ47UJyg==,iv:EHRqoYwA2xUKIeoqFr8IXH5GX1jis69SbwIzPz5wxXA=,tag:wZFZ7g7BRUCNWPnpfApM+g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:MCqGZoVguw==,iv:yOKht5vJEgAMF9tupk/acZXFxO9qFEamGgsEthMfMx8=,tag:Fh527vvaNRPGGf3n4LRTrw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:XMNXvmf76GZ6YRbSG76R7hsbu/trBvRGios=,iv:tqkwqDWdyRuZzTvt7jGHk1/tP+ryqkVXFaI2jH1S3QY=,tag:zxnitHTbIltjnX1TI+ofaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Mmc2aW5DRDlZOFVHakY0
            MEZEdWpmbTI0bWlJS0hUUlBFaENYWGRnSmhrCk80bmtjeUR5ei8zMUJXU0ZMZHY0
            UW8yTkNGa2UxYTFLQkxxcjF6OWIxSVkKLS0tIHd2R0tBKzZ1SGE1dFRvRi9ZZkty
            ZkZ3M3dBRFdhZDFBTmR3WVc1c09kd1UK+3Hj2OlmQADL6tUNNhgTcZYnTsWgpMTw
            dFyJtLzwxMfPM/aydXoLJZawZLkdww5qs7x4uZ/xyRaJdgynk3BHBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T11:00:55Z"
    mac: ENC[AES256_GCM,data:rWVHqiO240SG/IkPPG/4ZadBJ1eilxDPc746bgX/d019JcihtVrT0GyZUc41ubqCXXcm06QMDMuqsJJyrtXEgGPuYFMdF8urXBPstLozeC9XWIs/cum0FvFnrYc7YrPzR+iI42L7/ppeNp6NbPcOVON+DVFLqFSQbBx9uYldawc=,iv:sWLJsoz8maJcQ81pfYMVTFbiRWrfFtCw15sjSG/spLU=,tag:tdbmi9qEwwOiiAG3fBjRsQ==,type:str]
    pgp:
        - created_at: "2023-06-26T11:00:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdA7YX0+ZG7GKy9cVYU7A/vXZCS2HBfEs7nv2T5qzkFWCQw
            c4FQkJixiV/x5cx+MSkGpBLYse7tTwC9zJEuoo8gJsZjpCvyzGca2poMYoRsnXIT
            0pQB8EdAQN9MX2mnoVHUiusdgV13ew6CTWpEx9hBkVUUvZZ99HHsMMLCP1ysDFZu
            a1z5axfYRdCM+iIZFs1XiKcWGPvbeFZ6O0R9gYZqnGlibjce86B2a9RVaJ7alszD
            1lOvVumjUEKGAo/enM2PtwbtLulpxhbh61oFXcsQV1RZUZkjFjGYft+gc/cF6R0q
            Xb8UPRD/
            =6Lhz
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
