apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:KAgnqvg1cc8=,iv:Jz8NI6X6tDfuBdtwxpkRtHI2EEPrMBqEEvs5vzOQ1Z8=,tag:/NNeCgCqDYEpn8S9HDbxGg==,type:comment]
    GF_DATABASE_USER: ENC[AES256_GCM,data:ATQ9wmWbhg==,iv:fTtPxM+CUkNw4OLbe2k0Yvugr1bgKk8cX71wpWs/10Y=,tag:bw5tAxB1tr8/6pL+hwvbhA==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:6rO7G8HOZMgxQhecu3kQvnQnPiDN3SsuTbcMJYSb7Q==,iv:aw0aU09TbsgiJguzhwsg5y8s7NxsK7F6cblB2EVP3Bk=,tag:hl9Dg4XH9Sh83216bGqbKg==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:pXwVyh41kBhKwW/LcSANJPphklthJcvFNsATescw8nHsZMzuqGiGACBD,iv:vXrKxdjt77f7K9YobhnnFespxFagmujQdPpORtZnO7s=,tag:BjQ9yTOPjWVAwvjBM/Se+g==,type:str]
    GF_DATABASE_NAME: ENC[AES256_GCM,data:ULrA4+n8Qw==,iv:ZchixuxfVwUB72ApbVPaBUD/vEFer+cDV8EH4qs+njw=,tag:QQCcH/8qANht0+FcDB23yw==,type:str]
    GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:2h87DPpj4g==,iv:USZFPgj1ZwKAWlw+zOQo4PFEopaqBHxpO8rE4pQIMIY=,tag:fRXHkBe4qYpJlJm2e9Izsg==,type:str]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:OcxEk7FJPa4=,iv:f15EwunUrvhi++A8FZHzbHDRV8UlO0MkRXm6k1lJFiA=,tag:i/zcKtvZTEjuOOoNXkGHVw==,type:str]
    #ENC[AES256_GCM,data:FKSAGukMu0jnk1Jlc8cVc6QB+6wz4kuwU/ChIkXvJVPn1Yzg0L6Zgz2gpR+aZ05Baqwk2ky0e9wK4OChg8YXZuxAQXMxo4psCN8cdnwCJZSHlfgmFCvhgS3G,iv:DOWL0OwjFxW2QPvexyCs2Vgawaz2gzU5YOlsvHyDZVA=,tag:LuxmmA1S4fqc0Uc2zS5vBw==,type:comment]
    #ENC[AES256_GCM,data:3vz3HJicoOJkZG897Ow=,iv:o1Kh+nhL4BUCxBmSaQ18h7KfFyHEpIgI8pxWz0Tk+Wc=,tag:nAsl1PX6BuB7ceQ0QzFTJQ==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:e8B3X4XObQ==,iv:dXy1VPGDWab1nVR86AIiilbEvaRyxWuB8CihsKWs6Dk=,tag:DnmSmM5AVdI80lfj9nhN6g==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:D4U+ejzPFm2SdVplG+vTMZxE3whu8AJV3ZQpyOcOeRSzug9w3w==,iv:CC6jyMQcQKpNPtC4N1+09jjslTo/DN1+RpIVEVQdbEU=,tag:zH4xKUoo9YYbeNEB1HBzEw==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:3oNplcEa/0yzA3aegcmr+63L8Rec0l/eZNR6F2AhDsQlGXJ0GdB3c2HRAEtK8gdB8KZrxgtU,iv:GeNtlJlCmF3slOTGKldxdrfo+OASRaUvAHpawzmOsSY=,tag:0bmvJDbTxQBM7NvuMgeWzw==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:PvLNdx4AzoqJs8/+PBw2H3d8VcpA6OWZhfWFtZGGkQ==,iv:P9unoKqqpLL6Lz37+cjpmBq/u/zhhzz95AIvTDKYvBY=,tag:i2SfSAPDoWUo8Q14IcZneA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:x33IA0BvSA==,iv:9IYvqLmHQ9U4tLwAZgC5o4RSEGZs3qxkJJ8A2fWWtvs=,tag:4KanTc/VsFDcffG80A/QEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQlo5cnd0anVIQis1czdQ
            TTNRWmxwZWkxRWh1MCtXSU9seGoyQUpMeFJBClNNT1UrMUxhVzhxd2V6MW90SkVt
            MlRRQ0ZrdkZNai9oYWRLMnV2NlNkUGMKLS0tIFR5Wm5WSFc4b09TNTFnVkN2RWY2
            c1pxZUl1M2dzM1lremhPdm5maHp6TDQKeUNMhODnjTj7X3gseFZs2syasHm3lyeD
            lP21i9vU0MZIREtYcBri67TBEIjVmfsd7juhf7x0XzVfpv/8qSJhrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-01T10:11:15Z"
    mac: ENC[AES256_GCM,data:+dhmAXjAAkqwXYrzp/7mBD9i+VfA6pc2qUsXCjX/lvCOLpIwuJ+acpGTOuFZ9OtgXE+VyyGXBQn24CPTGYPYpFuzsgAlOqqSjXfbMi9trgXu7nhrpK/AliM1grpaCWZAdvD1Ps7/S/CsP3IJejw7eBECsCkaCcLak2xDz73u3R4=,iv:GLie0EcObfayS+OjAPCEdnFkHTSMpyQCjwiVKd2ihF8=,tag:C+b5RwUXeL6rk5+JvfH0ng==,type:str]
    pgp:
        - created_at: "2023-04-01T10:00:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAKSHBxtAwIcVQI6dZXafwaPgvFkyUck6eOmNQUVC3NUgw
            5qEQajsyehXf0gIBrT+8ZbMHDSDJSLt4+SPZJ5ldxIHbU6P2znCjKQ7HrAmmeVd4
            0pkBtm/GNf1mfZwd06tvZQiNHQ/GoCWQ1YxwO1Jf8SFatoscYmkmgsgVpVMFq6wv
            iDz2ibz+/UynXuGXY++rL4/K34HSfBFyMWaCIKrtLoyAa7WZscwS2YKx8zcfJsuS
            fqMCYNok+/tqDglZIdSW9uPEPXOLv5SQH26E5KSlnGliS2p7LrN24mdd2pf4rpMM
            uBoUzGTVQwQLpz4=
            =yHtX
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
