apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    gf_security_admin_user: elliana
    gf_security_admin_password: 'ekko95133:'
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
type: Opaque
stringData:
    # Grafana
    GF_DATABASE_USER: grafana
    GF_DATABASE_PASSWORD: Gusto.Outsell.Pueblo1.Equivocal
    GF_DATABASE_HOST: postgres-rw.default.svc.cluster.local:5432
    GF_DATABASE_NAME: grafana
    GF_DATABASE_SSL_MODE: disable
    GF_DATABASE_TYPE: postgres
    # GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OAUTH_CLIENT_SECRET }}" # from authelia
    # Postgres Init
    INIT_POSTGRES_DBNAME: grafana
    INIT_POSTGRES_HOST: postgres-rw.default.svc.cluster.local
    INIT_POSTGRES_SUPER_PASS: reprise:uplifting:radiation:riverbank:womanly:shelving
    INIT_POSTGRES_USER: grafana
    INIT_POSTGRES_PASS: Gusto.Outsell.Pueblo1.Equivocal
