# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io//kustomization_v1beta2.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-database-postgres-operator
  namespace: flux-system
spec:
  path: ./kubernetes/apps/database/postgres/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-as-code
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cloudnative-pg
      namespace: database
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-database-postgres-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-local-path-provisioner
    - name: cluster-database-postgres-operator
  path: ./kubernetes/apps/database/postgres/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-as-code
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
#---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1beta2.json
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: cluster-database-apps-pgadmin
#  namespace: flux-system
#spec:
#  path: ./kubernetes/apps/postgres/pgadmin/app
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: homelab-as-code
#  healthChecks:
#    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
#      kind: HelmRelease
#      name: cloudnative-pg
#      namespace: cnpg-systemkustomizekustomize
#  interval: 30m
#  retryInterval: 1m
#  timeout: 3m
