---
- hosts:
    - k3s-master-nodes
    - k3s-worker-nodes
  gather_facts: true
  become: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  roles:
    - k3s.haproxy
    - k3s.kubernetes
