---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: default
  labels:
    app.kubernetes.io/name: &name n8n
    app.kubernetes.io/instance: *name
    app.kubernetes.io/component: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
