apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-superuser-secret
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:LKiDDg==,iv:c09xL2TOzDViec0VGEmHdSiUqzc+B9VEanVuPJirqso=,tag:HWSNd7FqBQGtqfEX9ZQUKw==,type:str]
    password: ENC[AES256_GCM,data:NX1grh56f9jxJSLU7Gr+Ldh8vYXE3tDqj9Vyx11m+RJCYYskwspzJUxDKpn8kroNKqv7kxmG,iv:a6QJT1smBZ5GTZyCXy7tjDTY15KyHs5AojSttxsoMZg=,tag:5KiYb5BMqPWFKvhOgB2JKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdk0vY3ZIOTBCTUFocTNL
            MmlBNW1KSHBkem16UEdsWTNVcVJmcGNLN0MwCjZISjF1UXQ2aDAvbUJzR0ZVOEJa
            V3VQZVVaanpYb0dKUnUxWTBoQktRa0UKLS0tIDZKL3FjeHBxcWFtL3RyQzNYVzIx
            SzJIY1FrNEV5WlcvWEhxSDZxbXBvQmsKj0jzNBOean3ZRrjrrnTINECRdNIdA5hL
            bWueZ4rsZZ5hfmPZBmSYweXsBN5EcFtm2AVWmQ4oDtgi896HeE1SmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-18T21:07:51Z"
    mac: ENC[AES256_GCM,data:m2L/XA53rg1mvJy84YfJ8c7VY3slFwLVkXW+sQnxfwcRKP0ljeCSPJa2uMBjmeX8yQ+C2QNOL3o1lygg3hJIuOVCnf4QNzesnW6CLQcArQ4iLQhQLp24EZW4oJAHDgqaDr6AIqgv6w2ilJ2T6sJiWKJbuhN/1RudQQD28OPKn+g=,iv:khNQnactuVSMi31ey0Psicdgd2pr/i8vaq/q4EiNkFc=,tag:msAXIQCGfWQAXD2djaQvdQ==,type:str]
    pgp:
        - created_at: "2023-03-18T21:07:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAN/giUBuT+mNWsnGbsvqIRhKFxHm+etAk7WCUV2mh5ycw
            hlqVurlKJ3+5Rd9qTaFUyfR2O6aun87VuaesBYUChNCDbsV42IckxOoSvLjLvhJI
            0pUBTck+geH3yku7icuI+moIyAg3Fufr8woFFOKABJvlbwvCzkXeqqB1+L8vkMmb
            1Jxw7AlzW1T0MvWvFQdzuK+gwkLEElR28jNCXCWZV3Bzek1PCCik3uvXUppEQbw2
            0J8OpU53fS/COMJY0OB3df6XMYOqEX6kciEXwEOqTy+SB1T05iPKlPMe4ac7ox4D
            WtfiwgkzxQ==
            =o5Ag
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
