# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 8.0.2
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 5m
  values:
    gitea:
      admin:
        existingSecret: gitea-admin-secret
      config:
        APP_NAME: "The Homelab Git"
        database:
          DB_TYPE: postgres
          NAME: &sql_db gitea
          HOST: &sql_host postgres-rw.default.svc.cluster.local
        server:
          DISABLE_SSH: true
          DOMAIN: "git.zynthovian.xyz"
          ROOT_URL: "https://git.zynthovian.xyz"
          ENABLE_GZIP: true
          LANDING_PAGE: login
          LFS_START_SERVER: true
        "git.timeout":
          MIGRATE: 1000
          MIRROR: 1000
        respository:
          DEFAULT_BRANCH: main
          DEFAULT_PRIVATE: true
        admin:
          DISABLE_REGULAR_ORG_CREATION: true
        security:
          PASSWORD_COMPLEXITY: "lower,upper"
          MIN_PASSWORD_LENGTH: 12
        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: false
        mailer:
          ENABLED: false
        cron:
          ENABLED: true
        ui:
          THEMES: catppuccin-mocha-pink,catppuccin-mocha-maroon
      #additionalConfigSources:
      #  - secret:
      #      secretName: gitea-app-ini-config
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      podAnnotations:
        reloader.stakater.com/auto: "true"
    postgresql:
      enabled: false
    #podSecurityContext: # <- Default value
    #  fsGroup: 1000
    #containerSecurityContext:
    #  allowPrivilegeEscalation: false
    #  capabilities:
    #    drop:
    #      - ALL
    #    add:
    #      - SYS_CHROOT
    #  privileged: false
    #  readOnlyRootFilesystem: true
    #  runAsGroup: 1000
    #  runAsNonRoot: true
    #  runAsUser: 1000
    service: {} # Built with kustomize
    persistence:
      enabled: true
      existingClaim: gitea
    ingress:
      enabled: true
      className: nginx
      annotations:
        hajimari.io/icon: mdi:code-json
      hosts:
        - host: &host git.zynthovian.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    resources:
      requests:
        cpu: 15m
        memory: 226M
  valuesFrom:
    - targetPath: gitea.config.database.USER
      kind: Secret
      name: gitea-app-ini-config
      valuesKey: db_username
    - targetPath: gitea.config.database.PASSWD
      kind: Secret
      name: gitea-app-ini-config
      valuesKey: db_password
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: StatefulSet
            metadata:
              name: gitea
            spec:
              template:
                spec:
                  initContainers:
                    - name: init-db
                      image: ghcr.io/onedr0p/postgres-initdb:14.7
                      env:
                        - name: POSTGRES_HOST
                          value: *sql_host
                        - name: POSTGRES_DB
                          value: *sql_db
                        - name: POSTGRES_SUPER_PASS
                          valueFrom:
                            secretKeyRef:
                              name: cloudnative-pg-superuser-secret
                              key: password
                        - name: POSTGRES_USER
                          valueFrom:
                            secretKeyRef:
                              name: gitea-app-ini-config
                              key: db_username
                        - name: POSTGRES_PASS
                          valueFrom:
                            secretKeyRef:
                              name: gitea-app-ini-config
                              key: db_password
