# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
  - ./volume.yaml
commonLabels:
  app.kubernetes.io/name: gitea
  app.kubernetes.io/instance: production
  app.kubernetes.io/managed-by: kustomize
