apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
type: Opaque
stringData:
  email: "elliana.perry+pcufrixn@gmail.com"
  username: Coagulant1429
  password: Overstep1.Attitude.Sinister.Errand
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-app-ini-config
type: Opaque
stringData:
    db_username: gitea
    db_password: Excursion.Scanner.Recapture.Movable6
