# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:v4HOUtG6LNnsj7FcPHE=,iv:uweE8Tjo1lNpBqYFqUV8SI4vt+brTc/57JpXFDoIr6c=,tag:LT+5fr01H/STaHoqg3yxLg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:MkilJ5sZnYPZ4kievrdc8Q3l/dE=,iv:jD2akPEfkhTPmo8OQWAD2W8W+7oOtXkZ0h3GHhewSuA=,tag:HOrzHYW+HKuaP4am29oQLg==,type:str]
    NFS_SERVER_FQDN: ENC[AES256_GCM,data:WU6XqZcNbhKVEhrVxzHhzMnGSWVCQHkq,iv:Onmsnflm38BTrTuS1Y4n15oierM/G/IvvhQ/+Lxt2/U=,tag:HZff9L4t+Gi33qQ4K5Y3nA==,type:str]
    LONGHORN_NFS_BACKP_PATH: ENC[AES256_GCM,data:6CatEqJHwORI/YTiclA=,iv:nnj/SHeQNJjX6T+DfUZI35m4GzUyJQuVQMlFVENCbh0=,tag:+3IchpH/A91ZIKuqGMxkfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16atsrnff28efjkx3c5hmy88gwgwv5cpma0xkyjjw95vcw8kstp9sf4lf7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMnpMRy9MbHFMYXEvNGZv
            WVEwZmZQOHNCV0RHY0c1a0JJeEx3QzIzNzJRCjdlNWIrQ2NxbElyS1I5eHhWNUhY
            TkFiM05NNWJITFFCeWpzTjdQRHpPNlUKLS0tIGljajMyY1c1VVJVRmJ6ai9OcW45
            MG5mdS9oTncwa0Q3MWE4VUkrV2h6QzAKYHisKicYSiyRtQRpZYCMWLCK4tnYai5h
            LJQvvqsX3AuvP9rjxBK8AlzASNoAa+9+qvD/BwVAeRK4r5psZ0EnmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-14T12:19:17Z"
    mac: ENC[AES256_GCM,data:vX5b4+vgIfhaGO0gCt24f3aVAz3C5ix1qIr6qsrXSt056wJg9WQbRkE2yBWftU+YlInHGg+SGEilW1BTUI5WT/1M8xiiIN6EVyD4yM8FDBH3bz/Xn8YfdBMenqE0CD7xUBYCChPUz4e/J53IaNBI0TDvnf5NF2dPK9ckzRUeuTg=,iv:53aTzSmIGx54T5e6UMWrRx0cYV66lNM65PwGS48bPLg=,tag:r3DJ51EL2xzmiix05Y0Otg==,type:str]
    pgp:
        - created_at: "2022-12-14T12:19:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGLAzzcuyRg0rbSAQv4xOrQ2NiQX6Q+emzv7CQtwKMRyGR6eTFjNxoT7mWw7dAK
            aLKNSB7XgHl2GxfBCZX0RIivMV8n0Tp7/fHHPcxkRXjFFaThna+c9Caa8xjTNVhA
            dsJQA/FsR3BgpSqKiHr1fsKH9SijAV8LswiGf90YgsOOgtdnieE2txBVIJtV54T+
            5qncmJ6fAUWWFaxViOLKgcdWHKfOCQql7xtWPBAPTfryMXSH27cT3aO8QO5D8npQ
            luRa6OgAoMJbzxsDGzcRF4v1jA8c+i3hXfMiE5LnneNHlviZk1a0soiR54R8mAiQ
            /yhxlWj2hMeyBjRURm97OEqZ3hgVZkcvk+OKld+yE5eLAi2okdlD83LYG+1nVnBY
            vu1yyw55cT0Uiy0IKkhrU1Fhb5aqhomj1HGuO92ImibqPgp9ybqGXKaE/FCxNQHs
            Lu/iWix4aG20ojvVaoR9WokX3q7QFKb4Zpq+hxiZSnVY/jtFFzEh0o5tNISmkpS0
            7+8cbm/YosLGvQWPGA/SXgGjLhvrtVunRGFCyEzMijcIAfgOdg0ezIGoU+rR3kFq
            IZ8DQbvfP/HZqNmWokHLNpzKPojBTV/FWOqjOzaDEthU5PlZC9/WUXyuVus9HCs/
            iWFwASvEH0XvqZvjm9s=
            =lr5l
            -----END PGP MESSAGE-----
          fp: 90AB4A0FF0F17A5CAC2AEABAA538A7E3EC07999A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
