---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Detroit"
  # ! Match this to the original
  METALLB_HTTP_INGRESS_ADDR: 172.20.0.1
