apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  selector:
    # Editor complains if spec.selector is empty, despite using fancy kustomizations
  template:
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: default
      dnsPolicy: Default
      containers:
        - name:
