apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: private-flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: private-flux-system
  url: ssh://git@github.com/tkpegatron/iac-private
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: private-flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: private-flux-system
