---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-wikijs
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-longhorn
  path: ./kubernetes/apps/default/wikijs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-as-code
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: wikijs
  interval: 30m
  retryInterval: 1m
  timeout: 5m
