apiVersion: v1
kind: ConfigMap
metadata:
  name: crdlibrary-files
  namespace: default
data:
  default.conf: |
    server {
      listen 80;
      location / {
        autoindex on;
        root /var/www/;
      }
    }
