apiVersion: v1
kind: Secret
metadata:
    name: external-dns-bind-secret
    namespace: monitoring
type: Opaque
stringData:
    tsig-algorithm: ENC[AES256_GCM,data:fOFtzvkBTI29Ay8=,iv:a94ihNFOLgC5kXRLAUVyigqtaOopXM8W5siCEt5iF9o=,tag:aw8zZO2oNil1Qpkj2wM2mA==,type:str]
    tsig-secret: ENC[AES256_GCM,data:DfxAE4R1fNV+7q8QdTY7bY+wCXDDKWSSwNYTl0l8kzwJ/UJjgt6FUiDCOR0=,iv:5QPevmLxYbZkz0Vrbid4npWNyQKHwcLJgH+hzjwosH4=,tag:8eK9G+qaQMoLFD6BNcLVfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTnpsMmRraWIrT0YrQWsz
            N1NvNUtYWTN2a0dzR2RlZkkzbkhhYnN3bDIwCnpYU0VLdjF2OG5XOHdvZ3ZKU2NK
            bXVrb2s3dFFJRzJabVZOSmZYMTRac2cKLS0tIFZvQXZIcmJ6cHBWb3FZRkhsZVBt
            THVGaytEenlsSVdLa0ZQVTFhLzRFQjAKbYcKXrvltD6VHN8pEBK611aFxbeK5Af3
            LNJrCbU5fYpDVR0Y9x2sz3yGl1bOKCiWcSsQv4ijIjsMX15MiwGAkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-17T01:04:22Z"
    mac: ENC[AES256_GCM,data:c85sQI5A08U3n7kqyDOQ6PjtwNV1+rHAq4CndarmsDCae1UqRmSldNA1iJP9vyMhdOCzwEUDStNM3j2/EN/u6AnLeUiA5x4qVB0+9kAdirUt1/rwzsjtSlPUO43Dkz/OfFymRgXeh4a3pQV5HGXtFQnx+8HACMMFmb9dxQfJrz4=,iv:xSSOPfSvC5wYhWxbsspE4eGe17AD7t9PPHBrfy+LBw8=,tag:b5ZA12WkHo0S0mSGk9cRwA==,type:str]
    pgp:
        - created_at: "2023-06-17T01:04:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAC/PMg24IlqgrplCz9YzNq+Bu0oI6pHrtJRA/y9OxIjkw
            AAde8hmghYIWGD4hR5KT3MvS2/c88D33scbHyqx3KWYO9cNphk5qGMJhef6gmGvI
            0pMBZP4gZdM650JG4W3/l/DCazyOYJT6T0ylplDa7siw3JPQTsEmGF6fB9fD5fhI
            8mqyrUt24Fm6GdXHKzwePIg36rZUHB9S3t2IUd08V2ow6O2+6caihjcT65YoksJJ
            taBYgJoDUTuWB+L/f2KUcO29jm9N3rC4r44V4520crJVUgOZidj5e0AunxzGEreg
            7BqpNYo=
            =zNr/
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
