---
- name: Tune kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-routing.conf
    reload: true
  with_dict: "{{ sysctl_config }}"
  vars:
    sysctl_config:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.forwarding: 1
      net.ipv4.conf.all.rp_filter: 1
      net.ipv4.conf.default.rp_filter: 1
      net.ipv6.conf.all.forwarding: 1

- name: Configure nftables
  notify: 'reload-nftables'
  with_items:
    - src: nftables.conf
      dest: /etc/sysconfig/nftables.conf
    - src: main.nft
      dest: /etc/nftables/main.nft
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: u=rw,g=,o=
    validate: nft -cf %s

- name: Disable firewalld
  ansible.builtin.service:
    name: firewalld.service
    state: stopped
    enabled: false

- name: Enable nftables
  ansible.builtin.service:
    name: nftables.service
    state: started
    enabled: true

#    - name: "Netfilter Tables | Install Configuration"
#      notify: 'reload-nftables'
#      ansible.builtin.copy:
#        src: "{{ item.src }}"
#        dest: "{{ item.dest }}"
#        owner: root
#        group: root
#        mode: 0600
#        validate: nft -cf %s
#      with_items:
#        - src: "../files/configuration/{{ ansible_hostname }}/etc/nftables/main.nft"
#          dest: "/etc/nftables/main.nft"
#        - src: "../files/configuration/{{ ansible_hostname }}/etc/sysconfig/nftables.conf"
#          dest: "/etc/sysconfig/nftables.conf"
#
#    - name: "Netfilter Tables | Adjust Services"
#      ansible.builtin.service:
#        name: "{{ item.name }}"
#        state: "{{ item.state }}"
#        enabled: "{{ item.enabled }}"
#      with_items:
#        - name: nftables.service
#          state: started
#          enabled: true
#        - name: firewalld.service
#          state: stopped
#          enabled: false
