---
- name: Tune kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-routing.conf
    reload: true
  with_dict: "{{ sysctl_config }}"
  vars:
    sysctl_config:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.forwarding: 1
      net.ipv4.conf.all.rp_filter: 1
      net.ipv4.conf.default.rp_filter: 1
      net.ipv6.conf.all.forwarding: 1

- name: Configure nftables sysconfig
  notify: 'reload-nftables'
  ansible.builtin.template:
    src: sysconfig/nftables.conf
    dest: /etc/sysconfig/nftables.conf
    owner: root
    group: root
    mode: u=rw,g=,o=
    validate: nft -cf %s

- name: Configure nftables
  notify: 'reload-nftables'
  ansible.builtin.template:
    src: nftables/main.nft
    dest: /etc/nftables/main.nft
    owner: root
    group: root
    mode: u=rw,g=,o=
    validate: nft -cf %s

- name: Disable firewalld
  ansible.builtin.service:
    name: firewalld.service
    state: stopped
    enabled: false

- name: Enable nftables
  ansible.builtin.service:
    name: nftables.service
    state: started
    enabled: true
