---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-syncthing
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-longhorn
    # - name: cluster-apps-rook-ceph-cluster
  path: ./kubernetes/apps/default/syncthing/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-as-code
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: syncthing
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
