---
- name: Configure kea dhcp4
  ansible.builtin.template:
    src: kea-dhcp4.conf
    dest: /etc/kea/kea-dhcp4.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=
    # Fobidden mode?
    # mode: 0644
  notify: Restart kea dhcp4 server

- name: Start and Enable kea dhcp4 service
  ansible.builtin.service:
    name: kea-dhcp4.service
    state: started
    enabled: true
