- name: Create user account
  loop: "{{ general_users }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    comment: "{{ item.comment | default(omit) }}"
    append: "{{ item.append | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    groups: "{{ item.groups | default('users') }}"

- name: Allow user to sudo without password
  loop: "{{ general_users }}"
  when: item.nopasswd
  ansible.builtin.copy:
    content: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    dest: "/etc/sudoers.d/{{ item.name }}"
    mode: u=rw,g=r,o=r
    owner: root
    group: root

- name: Add authorised ssh keys
  loop:
    "{{ q('subelements',
          general_users,
          'public_ssh_keys',
          {'skip_missing': True})
      }}"
  ansible.posix.authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"

- name: Clone user configuration repository
  loop: "{{ general_users }}"
  become_user: "{{ item.name }}"
  when: item.dotfiles_git_url is defined
  ansible.builtin.git:
    repo: "{{ item.dotfiles_git_url }}"
    dest: "/home/{{ item.name }}/.dotfiles"

- name: Run user configuration install script
  loop: "{{ general_users }}"
  become_user: "{{ item.name }}"
  when: item.dotfiles_installer is defined # Relative path inside git destination
  ansible.builtin.shell: "{{ item.dotfiles_installer }}"
  args:
    chdir: "/home/{{ item.name }}/.dotfiles"
