{
 "title": "Speedtest-Exporter Dashboard",
 "description": "Dashboard for Speedtest Exporter https://github.com/MiguelNdeCarvalho/speedtest-exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Status of the Speedtest-Exporter",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_up" }
   ]
  },
  {
   "title": "Speedtest Server",
   "type": "stat",
   "description": "ServerID of the last test done\n\nGood resource for mapping ServerID values:\nhttps://williamyaps.github.io/wlmjavascript/servercli.html",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_server_id" }
   ]
  },
  {
   "title": "Gauges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_jitter_latency_milliseconds"
    }
   ]
  },
  {
   "title": "Graphics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Download Speed (Mbits/s)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "speedtest_download_bits_per_second",
       "legendFormat": "Download Speed (Mbits/s)"
      }
     ]
    },
    {
     "title": "Upload Speed (Mbits/s)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "speedtest_upload_bits_per_second",
       "legendFormat": "Upload Speed (Mbits/s)"
      }
     ]
    },
    {
     "title": "Ping and Jitter (ms)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "speedtest_ping_latency_milliseconds",
       "legendFormat": "Ping (ms)"
      },
      {
       "expr": "speedtest_jitter_latency_milliseconds",
       "legendFormat": "Jitter (ms)"
      }
     ]
    }
   ]
  }
 ]
}