- name: Install vsftpd
  ansible.builtin.dnf:
    name: vsftpd
  notify:
    - start vsftpd
  tags:
    - package
    - vsftpd

- name: Configure vsftpd
  ansible.builtin.copy:
    content: |
      anonymous_enable=YES
      local_enable=NO
      write_enable=NO
      local_umask=022
      dirmessage_enable=YES
      xferlog_enable=YES
      connect_from_port_20=YES
      xferlog_std_format=YES
      ftpd_banner=Welcome to homelab FTP service.
      listen=YES
      listen_ipv6=YES
      listen_port=21
      pam_service_name=vsftpd
      userlist_enable=YES
      tcp_wrappers=YES
      pasv_enable=YES
      pasv_min_port=60000
      pasv_max_port=60029
    dest: /etc/vsftpd/vsftpd.conf
  notify:
    - restart vsftpd
  tags:
    - vsftpd

- name: Get installation media
  ansible.builtin.get_url:
    url: https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.2-x86_64-minimal.iso
    dest: /tmp/

- name: Extract installation media