---
- name: Restart kea dhcp4 server
  ansible.builtin.service:
    name: kea-dhcp4.service
    state: restarted

- name: Restart kea dhcp6 server
  ansible.builtin.service:
    name: kea-dhcp6.service
    state: restarted

- name: Restart kea ddns service
  ansible.builtin.service:
    name: kea-dhcp-ddns.service
    state: restarted

- name: Restart kea control agent
  ansible.builtin.service:
    name: kea-ctrl-agent.service
    state: restarted
