# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io//kustomization_v1beta2.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-database-mysql-operator
  namespace: flux-system
spec:
  path: ./kubernetes/apps/database/mysql/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-as-code
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: mysql-operator
      namespace: mysql-operator
  interval: 30m
  retryInterval: 1m
  timeout: 3m