---

- name: Execute FRR Tasks
  when: routing_type == "frr"
  block:

    - name: Spool in tasks for FRR on RHEL-like distributions
      ansible.builtin.include_tasks: redhat.yml
      when:
        - ansible_os_family == "RedHat"

    - name: Spool in system tuning tasks
      ansible.builtin.include_tasks: system_tuning.yml

    - name: Spool in FRR configuration tasks
      ansible.builtin.include_tasks: config.yml
