---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  NET_NODE_CIDR: "172.20.0.0/25"
  NET_POD_CIDR: "10.42.0.0/16"
  NET_SVC_CIDR: "10.43.0.0/16"
  NET_EIP_CIDR: "172.21.0.0/16"
  SVC_NGINX_ADDR: "172.21.0.0"
  SVC_SYNCTHING_ADDR: "172.21.0.1"
  SVC_SYSLOG_ADDR: "172.21.0.50"
