# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:iRU7vKoOfxeVclbGwjsfOvyDMziZ96Xl93Ntyjis,iv:Ly5qWrXMdybiYPfnhizzXeGHiitF4FO+VDarbHsPIis=,tag:Io8wNrVwylxkP2VqXY7rKA==,type:str]
    SECRET_ALERTMANAGER_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:HMvKGedQwqhCG+KyIFq1xMow9k+Lru35uQ2xpAk7,iv:Ujp7NtfSsePca/KDDjcxdxQuIuXz9E7YLVjRvR74LwM=,tag:KNkywGislkORPJ4axoiYww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZjZxc2wzaHd5SXozZWh1
            T2p0RzZqSzZnNWdXM25MYkhNcFV0MUtoR1JjCjVSMjY1Q0FwcHZnM2FmRktCZGl3
            VmcxRG4zQkdGeXBYSlU3d0FVajdncGcKLS0tIDUzNHFYTkp6QjhnOEtDdU9vRGZl
            N3Q0U3JFeHliR3dlZExhQ0dsdG01ZGsK5EFol7/89WY7Das1J8emjHhAdexgB2p1
            pk0Adte1R3ML+wjPJ21j9qZhPPFJrwuIKFX/xpvrt4XpARRlb812fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-21T18:56:10Z"
    mac: ENC[AES256_GCM,data:l6t5uabWt5WBMne5MBx4jhXW4BHURi3ur2IF6axfJc3UeURBVcO0TdDBsRM1psRLBMMSGyNnRqD42IVCzRSRs5smapK02ANwUqmgOc7lKhzDYaLP+oPM+J7P5t1iPW3RKjtlCsdxETuT0FqBng6cop3LK1kSQYMZhDrNty+qZTw=,iv:8VxJvJhfdecuClQpNA84wQokOS+VnyZVLlMk3OdHX/A=,tag:kyjL7bLIsnYnpSCm2zxBbQ==,type:str]
    pgp:
        - created_at: "2023-03-12T20:19:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAp2g0IdVEJq8tYX1sCy4rxuGBPpHLMfFaWX6g0CL4o1kw
            SoPygFNBKMft2p2fNp0atVBHvB5I4Ho5sXIxrFHY7GWVLOLGYvcetxompVsfWxp4
            0pQBu6xkEbU+3s7drfXmbOfeNvmoXeyL4V97Y60eRUd5qi5DYiHpBbiY+lILxUeG
            Avz6xL+75ttDSa/sW5z+9pazuS/KnGgAPqhIITGq10rqRrGodgRymBRVTI/+4RH7
            7i8oi5AJ0+zLS0ilCQczRVP4C4iHF0HttNOrKvsvNJIEMozzFQgAZZ9gIQ6dwJ+X
            VnCjXzbe
            =gjdq
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
