---
# yaml-language-server: $schema=https://kubernetes-schemas.zynthovian.xyz/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-database-redis
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph
    - name: cluster-apps-local-path-provisioner
  path: ./kubernetes/apps/database/redis/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-as-code
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: redis
      namespace: database
  interval: 30m
  retryInterval: 1m
  timeout: 3m
