- name: Restart BIND
  ansible.builtin.service:
    name: named
    state: restarted
    enabled: true
  become: true
  listen: "restart named"

- name: Start BIND
  ansible.builtin.service:
    name: named
    state: started
    enabled: true
  become: true
  listen: "start named"

- name: Restart Unboundd
  ansible.builtin.service:
    name: unbound
    state: restarted
    enabled: true
  become: true
  listen: "restart unbound"

- name: Start Unboundd
  ansible.builtin.service:
    name: unbound
    state: started
    enabled: true
  become: true
  listen: "start unbound"