apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: syncthing
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    image:
      repository: docker.io/syncthing/syncthing
      tag: 1.23.4
    env:
      PUID: 1000
      PGID: 1000
    service:
      main:
        ports:
          http:
            port: 8384
      transfer: # Trans! :P
        type: LoadBalancer
        externalIPs: ["${SVC_SYNCTHING_ADDR}"]
        ports:
          tcp-transfer:
            port: 22000
            protocol: TCP
            primary: true
          quic:
            port: 22000
            protocol: UDP
      discovery:
        type: LoadBalancer
        externalIPs: ["${SVC_SYNCTHING_ADDR}"]
        ports:
          udp:
            port: 21027
            protocol: UDP
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Syncthing"
          gethomepage.dev/icon: syncthing
          hajimari.io/appName: "Syncthing"
          hajimari.io/icon: mdi:folder-sync
        hosts:
          - host: &host "{{ .Release.Name }}.zynthovian.xyz"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: syncthing
        mountPath: /var/syncthing
    resources:
      requests:
        memory: 75Mi
        cpu: 100m
      limits:
        memory: 300Mi
        cpu: 500m

