---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing
  namespace: syncthing
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
