apiVersion: v1
kind: Secret
metadata:
    name: syncthing-restic-config
    namespace: default
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:XcceN+Rh/CRR2zLBNpC+ka5CFV4y4tRflfxht4EQSulGC1RLEpr8Dm9gK5y+GUoIwvzwZklF,iv:KPA+RlRpeSWgCXV7xN1RLn84AVABXu8WN+I+0wYijlw=,tag:LZnuqBc0yThsV3Rk4PZQFw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:mNS1IIjfKTw/0G25p2j3Ouj/SFiQ7ivdRJYK75Cdyks=,iv:0bA7XWhjGG7KcXDfcAvUq+jhZzrOCGxD1WC4JfwYCaI=,tag:skuFFWM4Qp3fWWkIxBqZjQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pXoq0QVU8bJCXPE/2spFH20ayDnwIkOanFME3eWwjac=,iv:rKJsen434k1CDHePuB9QcLAKM6iyDXJDaTOdydlJgzM=,tag:+iSjbG54SnWlAw3YAi9sCQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:x50z3jAbpXcsODSBqLE+Ow==,iv:wqbXveq++RlYm5Z/058O0/as1/YU6QhOKiAs1Jf01H4=,tag:FdCg97RN2nCpKRD/c1OZZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU0dhZ093M2xhUTVWdVhU
            Q005bzkrbGdJenJzVm5WT2tQY1puTEJ6QzJnCjR0TFQ1dXVDUUtOY1FoaVRSeXJS
            SEVZRDZVa3pRMUFsWklFY05FeXNFZlEKLS0tIGlsT2l2Y0NueFJXbkF3UXA5YUYw
            U0ozcWhZb1d0UXhWVnpYeWVnN3dCR2cKtqjLFxjncETQStucilpPfB97py12HP4D
            3w1MbDgAHH3eDgPbmG4IcCcRg//bZAIQOpo20RgL9YrOJWui8ApLdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-01T09:33:18Z"
    mac: ENC[AES256_GCM,data:wJH/gbrfoYreZkWG0WuyLGUZg/SGSfvRH41APXmbkLip+A3rGoEN4dkcgoUB2PD8soHx1ahgoQoyZM0HT3l/q8vp94ya2XzuXDntoQ6hulYA0/qqSRO0jOnsLWbS8j8F49SWxE1nnItduARlQxsJFoWD0FhvKGDUefCIFWFQQqc=,iv:657xZXgVmkgVMITp7D2+WZ4RU6WnwiZbS7BQ5LIxT8k=,tag:sK6FPHYK7oFBDwTGaBggRg==,type:str]
    pgp:
        - created_at: "2023-04-01T09:33:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAaONYwnfzfWLvvbWmmS+W1dmQqmIFnFNbS5az6CuCxmAw
            2IC3gqKCCXRkSTtumHmipJZ9/yg5wAyl344jc5/+/T8RuTXOL2OndPGsNSqsZ89N
            0pYBccQA5OygjE5T4oyUzDRNpOnR1wkFaXm5EVuPkchn1y9BItSnot+wPA4pHZyT
            0jveexBlK6EHRg9Vxw+uhORdvRNbFQi+ZJ8GGOUgPNHskvf8usrfwJ7US32a26BJ
            CaChz3mNDQh8YhoeTHKOa/PKv4/iKrBB4Sntawu79ibmQ6kGUZo0NwWI8C0tszLw
            SkDfobw+xcE=
            =dtvX
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
