apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: cnpg-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    spec:
      containers:
        - name: pgadmin
          image: docker.io/dpage/pgadmin4:latest@sha256:4119be73c1d4d94ac6ad96e5ba4fd78e049dde426a05a75db0a342baf0734353
          securityContext:
            runAsNonRoot: true
            runAsGroup: 5050
            runAsUser: 5050
          livenessProbe: &probe
            tcpSocket:
              port: http
            initialDelaySeconds: 10
          readinessProbe: *probe
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
