---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authelia
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  path: './kubernetes/apps/default/authelia/app/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-as-code
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: authelia
      namespace: default
  dependsOn:
    - name: cluster-apps-glauth
    - name: cluster-apps-redis
    - name: cluster-apps-postgres-cluster-default