---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authelia
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/authelia/app/
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-as-code
  dependsOn:
    - name: cluster-apps-glauth
    - name: cluster-apps-redis
    - name: cluster-apps-postgres-cluster-default
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: authelia
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
