---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      nameOverride: *app
      annotations:
        reloader.stakater.com/search: "true"

    image:
      repository: ghcr.io/benphelps/homepage
      tag: v0.6.17
      pullPolicy: IfNotPresent

    serviceAccount:
      # allow scraping of k8s resources for widget
      create: true

    env:
      TZ: America/Detroit
      LOG_LEVEL: debug

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host homepage.zynthovian.xyz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    service:
      main:
        ports:
          http:
            port: 3000
            targetPort: 3000

    persistence:
      config:
        enabled: true
        # type: configmap
        # name: homepage-config
        # mountPath: /app/config
        type: custom
        volumeSpec:
          configMap:
            name: *app
        subPath:
          - path: settings.yaml
            mountPath: /app/config/settings.yaml
          - path: widgets.yaml
            mountPath: /app/config/widgets.yaml
          - path: services.yaml
            mountPath: /app/config/services.yaml
          - path: bookmarks.yaml
            mountPath: /app/config/bookmarks.yaml
          - path: docker.yaml
            mountPath: /app/config/docker.yaml
          - path: kubernetes.yaml
            mountPath: /app/config/kubernetes.yaml
    resources:
      requests:
        cpu: 25m
        memory: 105M
      limits:
        memory: 225M
