apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
    namespace: default
type: Opaque
stringData:
  # App
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "${LDAP_SVCACCT_PASS}"
  AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "1cSfaxC6vxLGD8gVHVsr1qrQUusLciGI7K1IUBKEqdzsBAeHpT5DHxeS8bJerMea"
  AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCIWvtN8e6fVCCG
    b80CYMHaIR+Ir4OsCnRUWqOuOeba8l4Q7F1SPskuip0j013CfJdcAc8/jzVNVdeq
    IEjDNALrwdXBqWNZ5OjXhftdja75ZM6CCWv8Janb8QKxGKk7tlbRG1Vg7SIj1Evm
    VEClxbpfrTmiAdHtwUHSYLDLNLxM/2nB/dvrBIiuqGa2eRnC8X0EUem5+ibUQFh8
    TwHgKhX//Mzrncf7schMX252De4QUrAw4/MojDrOkcE+3tDRP/1wWa3+MWk2pib2
    M1VsOPMH5OCCGz0EuWFfKiOIWgAuin0YBpQ5UwmauONi5Bcnmv8jw/0ryNEKqY/p
    Sj1o1w46cBgQqDc1udg2ogc1TGzG2RJSWdxChr3FnZ6QAm09k9f7/ldjzGCdkZd/
    /MhYQ+MzywpCF6MAbwr4JqZf3pM+Ad2mx4UMYMNV4cSaq+RZ3i86M6//Mex7JtoZ
    TEuiR9iADmlCuSLnpJhIvxyL6CUGJxh8saj12UifTgiTd6ReCAUpexGTWG41HlWG
    t/JyKd7LokXUAUyk50uJNWDeAb3E5Q5M9QNiB3PCgyFHgysJG4g+ZDx0YlgCIi24
    0keMe9NVWObIDWNLi02Ey64NmCkCW9BWv4fIOCT7E8qYqaw4CuQMGnnM7xjx+i3B
    99FinY4bapyOb535Vr6p83UaTpxsMQIDAQABAoICAADV9xM880IRC6jZlXHUkpJ6
    AFt7RaY0UQ7MdAD3Gwlv9lA3q9PpOy8ItMOXdBVjY9WNHUnQKcQMuzmwTq+V6XWH
    WOwUHSc3VkYJo6KET8/4raSEH/ucQcbbWsO5/dQj3yDutxoeIyJKzbMnu1bbE2sY
    bnFvNNmkO+cNpmMz6UOR2Kb3L/XoQcdeAge9ctywwa5Gz/mqJSh/5+ZfvHYQcIxe
    Sgog1OPWo7Vh2YLqBl+LPaOF7+OgT0dmAwioMY5WzFwKOdPyMZboKmPUhLj0h0RD
    aAhR2CMMa0c7xJrYyT02pmNcdK1Hj+E5MgueRt8zRuCEGnUr9oU1EXDBx71wxk9B
    9NhmyZD3oSuCVMdNlaI6ADhztbUg01S0YrIuGTWfpTJxpcM5nWhQu8HLE1Vi7UvQ
    VtrtVV/uyepnTy3jWoyhGfvkcvXgIEG1OXbF8tmtwch9KoLei7bE3ng7/dJfDHI5
    pqJ/ZNJ8mgE8LApJz38CRotiVZkwrKqYh4nFxoHoiUuPm7KHKMZVpOqma6zG7olA
    9yxoxk7GMzwigG9E5bD0OSWhuSd9b/HyMTfA/UshZ3drWXhVqavXJeLZkOqf5nmn
    r3trec3dAYBqDbief2/3/n0ID+MUEoozhWPrh1uKX4GXWb4GNv3c0sBAAwMdVdoT
    KXrOjWEz2dCT3S/0ID0RAoIBAQDA1VhCD+ciB5ArUAECHv4n4J3U8GKo01g8PAIN
    oXv9jTqsZJJutSETD2xqr1Qr3PrlEZLpNuIpaeRR1zyj+9hsR97gno7ZUB3uKImy
    +7pXIsl5kLSL9qJBX8SKb4ieIZy6b5Ry5H5qiWVDYqM35WF59W3ucIFdOChqF4Ll
    fJG8i5x1Zk14lz2cbxUc3S4+ICtzA291l8SfxdCe4KtK6Dl3drhckFVftYIRNSvC
    dWZkR89qagFS/KQwj17ovEYLGdKNwvMzAo48z1YF33aq/PzurySeHpvxLkHgfN6Q
    d24rZJNgMSkESjVPObNUygmO2wfsZ6BrNWIBhNw9ME953GEHAoIBAQC1BX8Yypqq
    2HtyhtKl1nZDHe8xPxiEZ9A/LB4E1/NLqeypk/IsGyTTVU43Ec18pFbPJk6PdYHy
    Jw3z2JIjXva9bulPakoJjP9KzlIqfcyo5MXhXBUsJLaommbaZ4WgRY2CCfkW+R2q
    /ybrzRkIsXce2v1zkrQ4Pbhnf3A8CWkgSLE52frb6gsWOUiDwJCNgJnyiZ56rj6i
    vK1I7/UNQT8xQqScIuQKD3yf+W8xqHMdBDAA5wsZu0YdrF9cCYPTcA2dn9mF17FR
    z5OQAg2AQQbhjLIk1MgpKhOnXWCox2hE+dmXv+9TCVD/C8WAikWJKuT2qUvyz3BQ
    BoyNFkv/O9MHAoIBAQCRLo9afZqpdkRHN97qd+cmouhx7+J39VcTUqLBHHm7tl8c
    eEP/cgPK0+vujr6yn5eOa6LOT3ILeBxcuc6AMBcLvzjAqOAoITfHnWG/DeOHwzsp
    eZdVYYVb7vyMtdiIJgpYG7YKopnDIFrLVzJH3T18kxoHUVE0nBlhdv4oRZd7+yj7
    AuEFD+llJAUjTCuKvrG30DhUssVo/YhKdiDBLwJFPW8k0c5VVtTsm7msmLNUgPRa
    zCDfGDOOFAOC+m1J4lEyRjrQhvYMNpYvqcUwi3TrR5YsLiN+fDNBDwKKhkC+DuUe
    oSSehDiKw4iPJ+X2VlYq2QJgdTqqphsjPoI334J1AoIBAQCcsVJQCmiRhGxvOWcz
    qA2ckVfQIBa/3gDz/eNKPAfcsg0qyOay6RgaWtgmcSGXR8Xg7/7GzWebTdUVA52U
    QoqAdXY9iPrng4Ykoa2cHGLAu67SIVwuZuU50tU/LqcLkckpDCryiNb2goCVUmbe
    EIfVTKhhl1aq7DooVLa5MUgvat0F/7rXC6NnLFSpv1EhO3WG7TsiZJvRUFMLNLLB
    M35YzKAii00rrDYrX8WxjWd/cXWAAn6oWmQaIXA2AgJ7Tp5ql8i5w3g5Id5QpIY9
    Q4yKRriZixpsD4ENuZWG431NX5zLb5fhH8pdyzm9x3Ljhh7FqMwWNRu6GcEmC2vj
    VkyXAoIBAEa6NITijc9SZ/7mD47Uq5kqkEXmxvhRYkRWVPw18Lb7z71egOvIsBgV
    tq7SHmQ/EWIo8PDDwGZR7W0T2lc5KHtiP1UUbmB7DFRGVK+F5Bh3O6wVpPyOFklI
    iFGh9x5e65vAD4JnBSlGqOxuytPhYijEoUuV4RV2NgAXHizTdPZEaCVEuMMlsmEa
    0a+ObtGSiDkcta2aovSl+ZdsT8pUpGFom0wE3tfGbTb0/xrHHAIPOugHkkbbh0hG
    qpdCPHN/Gxqv5aTR2LBxs1syp/AVK2HdbGYM+jXsGtEkiBnFmhYJlKI2aI0Iv1qM
    k36dmYNvOVx07SmrbbXiA2F5FhtID5M=
    -----END PRIVATE KEY-----
  AUTHELIA_JWT_SECRET: "29tTJQqhRHgqW3VfWwfCcZ4MsAcLv21hbRu7DepwVzAMRA5LmwzU9QlFqKPcur1Y"
  AUTHELIA_SESSION_SECRET: "ZDqX5pqDyocxlVgf7g5gLDvpLprHlwhjiXcp9VqA6A3CSUG1oPnyOphGgfkDGEQK"
  AUTHELIA_STORAGE_ENCRYPTION_KEY: "qSFW5BqbFWcEZaVVYspTwi9ER3XoQjjVDfNbnt6pQZJWF3zlWCpK6SmvVFDQNELX"
  AUTHELIA_STORAGE_POSTGRES_DATABASE: &dbName authelia
  AUTHELIA_STORAGE_POSTGRES_HOST: &dbHost postgres-rw.default.svc.cluster.local
  AUTHELIA_STORAGE_POSTGRES_USERNAME: &dbUser "authelia-sa"
  AUTHELIA_STORAGE_POSTGRES_PASSWORD: &dbPass "GTYpPovv1zuo0pag8kISssF2SExmqYXan1cmgOnNfSVNQ6qvfHj81KncT3B8PmtA"
  GRAFANA_OAUTH_CLIENT_SECRET: "${GRAFANA_OAUTH_CLIENT_SECRET}"
  # Postgres Init
  INIT_POSTGRES_DBNAME: *dbName
  INIT_POSTGRES_HOST: *dbHost
  INIT_POSTGRES_USER: *dbUser
  INIT_POSTGRES_PASS: *dbPass
  INIT_POSTGRES_SUPER_PASS: "${POSTGRES_SUPER_PASS}"