---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eperry-syncthing-data
  namespace: eperry
spec:
  volumeName: eperry-syncthing-data
  accessModes: [ ReadWriteOnce ]
  volumeMode: Filesystem
  storageClassName: longhorn
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eperry-syncthing-data
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: eperry-syncthing-data
