---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-data
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
