---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app wikijs
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    image:
      repository: ghcr.io/requarks/wiki
      tag: latest
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: *app
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.8
        imagePullPolicy: IfNotPresent
        env:
          TZ: "${TIMEZONE}"
          POSTGRES_SUPER_PASS:
            valueFrom:
              secretKeyRef:
                  name: cloudnative-pg-superuser-secret
                  key: password
        envFrom:
          - secretRef:
              name: *app
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    service:
      main:
        ports:
          http:
            port: 3000
    persistence:
      data:
        enabled: true
        mountPath: /data
        existingClaim: wikijs
        subPath: wikijs
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: file-document-multiple
        hosts:
          - host: &host "wiki.zynthovian.xyz"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 1000Mi
