---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - secret.sops.yaml
  - volumes.yaml
commonLabels:
  app.kubernetes.io/name: wikijs
  app.kubernetes.io/instance: wikijs
  app.kubernetes.io/managed-by: "kustomize"
