# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: wikijs
    namespace: default
stringData:
    #ENC[AES256_GCM,data:xJUxWXNT8w==,iv:HMkGVhsmJSk/rWoDcz5ESxE6fyoyM64Bwr4ifdBl7DE=,tag:BNgcpyYyT8WqUM1x2l9yMw==,type:comment]
    DB_USER: ENC[AES256_GCM,data:MTO1mbJT,iv:oJiXVIPa4euoE3Jl2r9sOsl1tSojf2tlkWjpgwkePJ4=,tag:Fl59HlNZyI4y2BiKtsMQnw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:efPN3Ef0,iv:zYdiBq4vQ44dkZJGm5SxtfYAG41ckMaCaRhGT+mqBa0=,tag:PLBkiD9zXE1adWHZ/gt0/g==,type:str]
    DB_PORT: ENC[AES256_GCM,data:AR4+rQ==,iv:pO1WIai+2V6wcu2A8vq8S4VjYAzUNivIhzchiD5Brko=,tag:XZWtrXotB8uMSo1Xk0XAEQ==,type:str]
    DB_TYPE: ENC[AES256_GCM,data:qgy6X0ZpkwM=,iv:Ubp5o5AQ+JmTdCcJzCjTElxESPq08ZaFeofb5f3NLd0=,tag:IToLZhABIP7LgQnh2jLp0Q==,type:str]
    DB_HOST: ENC[AES256_GCM,data:EoS2BwxqfUWLvHqz47BpBWGrgokALwtX54gyGGnFtWg4cDLHzQ==,iv:wjJQyWYAHg51YOb2aDQ6Ie3LYNvdDO3rmOTNGO7BgPw=,tag:LowCDlszwL+XtKg3BfhQXw==,type:str]
    DB_PASS: ENC[AES256_GCM,data:YPHfY/8BxMhqCx85NLHxf7RATDoyG+d+uWxNTGe/zSQ3vhPNPEBaZyJZgFFF/XENMZj0uA4=,iv:SP3KyiPCdXNM5KYBo7panz8S3rCUZaQLwjIa6vwGk7k=,tag:hXowOq+0MhOnz2A1uYshiQ==,type:str]
    #ENC[AES256_GCM,data:4N1nTi5WkTTW8duyzms=,iv:G/LENKRyvXAnt4PLj01zu+CvF7eqmyaC5TU2E5++6v4=,tag:qGs800yrA0ckTttrdw75ww==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:WEGWKOTr,iv:yaodYfK3KScP/kHOwhH1FWx+a4oyWFK27Kaz07Y9U+o=,tag:r/A+jj8BQGWxNK7d590HTA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:XdjA0uWIjNwyLhHbQU2A5ZZXdoEYHdGVlTuu99XYxyD7rahHZA==,iv:sU3iv8kY+6FXVjvuMh0BgzAkJTBSY45UhGf0RIbFRwE=,tag:IvevGfgNw97XfJbgP1mc4w==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:gZ4V54Xd7ek0v15WfrE4Tm1H4UIUzhP5OOrySGVjU83XJhaniQ1oENSOQOYCjh5Sb8t0SfY=,iv:/adQHOF1d/Uc7jO7ZfLia7LdwhOjETdQShMJO8y3TZ0=,tag:JN/qR15vMxtqEWap1LjbwA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:W3mlseeL,iv:4csu67FoDr9RlReWcEy3a+5HcXh/6TfwrV00k1oa4I4=,tag:YOmydYiSLDO5/8E8s1Qd9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeEJKYUhoWlg5YlNJaVJF
            Y1pXNUU3djhYckRHWmNYNlMyZ0lYNzJCWlRRCmFyYW5UYVgxK3ZiWFNCb2xHTlNn
            MGJwWGlTOWMzLzFDMTdVZHZvVU1UZjAKLS0tIDdWNWdkL0VpY1FkNEdyeVNpU3du
            bFJnYjljaUtGTEhIVHlUVlZhRzJsdVUKGT6Lkv5CNexRcEvkwYkvwbyz7cle+2Xs
            Zg17PwQGtmPNAKhNNv+uOmzteq7LTeB4n6yWrGFvs9C3Pp0HJfYxTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-19T06:32:16Z"
    mac: ENC[AES256_GCM,data:VFYpaC40RroQhHx8QkCTRJiCWm6/ngwS5P9A6BQAjiSEZuTtZGoid1Wih6vxdgNc4+hliVgEn7MTF0BXZ56o1cssY/eEapSHMF18aKQPC8M+4rDs+Y+puac5NP/Tc4/WfAulByEpWQQl7uHHlzouttVcDq++XN13Nle/ZSJf1vg=,iv:CJZTNek/5lBiM8ija91mLRj4srPRZbOLPHzm46aEAbE=,tag:F8JOIFyXfsytsomnTADbrg==,type:str]
    pgp:
        - created_at: "2023-03-19T06:19:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DuBz7K6VE7cMSAQdAOujOciiHql4fNfBeUinHNdbzE5o/IINTj/buEzqJBkUw
            7TfobPP1A57v7hII8ayYh3w3RAlMbdmpb3HuNpnNt8IYH/ePoCP7BsydJ4xq/NYS
            0pUBMxDLon1QH3vRXuA2ht5GcVtR9mU1jeiMkoCF5L4ZLPPpsa7suZ7IMuAURJ9z
            uaFOje54+Cm8nO4SKQZ8Gxh//BX3So0zww+PzNBRxoXL15K041KHERaCQouTCCMC
            qwKdfUVOTpSDGV1h/s/quDv8ZzS7w3j/XWuE/wgv1V5ojt3jWkTTiQW6WbQk0frn
            Dzuvl2+7MA==
            =VWho
            -----END PGP MESSAGE-----
          fp: 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
